<body>
  <div class="main">
  
### ¿Quiénes somos?

Relaciones Productivas en México es un Área de Investigación del Departamento de Economía de la Universidad Autónoma Metropolitana, unidad Azcapotzalco. Sus integrantes imparten docencia a nivel licenciatura y posgrado.

### Nuestro objetivo

Diagnosticar los principales obstáculos competitivos y organizacionales del aparato productivo mexicano; contribuir al diseño de políticas específicas que apoyen el desarrollo productivo de empresas, y aportar información y análisis conceptual sobre los fenómenos asociados a la generación de capacidades y competencias productivas.

### Nuestro objeto de estudio

Estudio de las transformaciones de la economía mexicana en el contexto de la globalización, desde una perspectiva meso-económica y considerando aspectos económicos, políticos y sociales.


### Equipo

#### Jefa del área

Dra. Josefina Robles Rodríguez.

#### Académicos

Dra. María Beatriz García Castro.\
Dra. Mónica de la Garza Malo.\
Dr. Juan Andrés Godínez Enciso.\
Dr. Jaime Alberto Prudencio Vázquez ([ORCID](https://orcid.org/my-orcid?orcid=0000-0001-5866-1280), [Google Académico](https://scholar.google.com/citations?user=p083DDsAAAAJ&hl=es) ).\
Dr. Edmar Salinas Callejas.\
Dra. Beatriz Paloma Sánchez Cruz.

#### Ayudantes de investigación

Leonardo Pérez Victorino.\
Francisco Gerandy García Rodríguez.

#### Servicio social

Diana Areli Lara.\
Rizieri Hernandez.\
Miguel Angel Cruz.\
Vania Cruz.
  
  </div>
</body>
